events {}

http {
    upstream nodes {
        server node1:8080;
        server node2:8080;
        server node3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nodes;
            proxy_set_header Host $host;
        }
    }
}
